/**
 * Mappa colore -> classi Tailwind (avatar bg/fg, dot pieno) condivisa da conti e categorie.
 * Copre i 16 colori base e le 32 varianti chiare/scure derivate (usate solo dalla
 * distribuzione automatica dei colori, non selezionabili manualmente nei picker).
 */

import type { SwatchColor } from "@/lib/validation/shared-colors";

export const COLOR_SWATCH_MAP: Record<SwatchColor, { bg: string; fg: string }> = {
  slate: { bg: "bg-slate-100 dark:bg-slate-800", fg: "text-slate-500 dark:text-slate-400" },
  blue: { bg: "bg-blue-100 dark:bg-blue-900/40", fg: "text-blue-600 dark:text-blue-400" },
  green: { bg: "bg-green-100 dark:bg-green-900/40", fg: "text-green-600 dark:text-green-400" },
  yellow: { bg: "bg-yellow-100 dark:bg-yellow-900/40", fg: "text-yellow-600 dark:text-yellow-400" },
  purple: { bg: "bg-purple-100 dark:bg-purple-900/40", fg: "text-purple-600 dark:text-purple-400" },
  orange: { bg: "bg-orange-100 dark:bg-orange-900/40", fg: "text-orange-600 dark:text-orange-400" },
  red: { bg: "bg-red-100 dark:bg-red-900/40", fg: "text-red-600 dark:text-red-400" },
  teal: { bg: "bg-teal-100 dark:bg-teal-900/40", fg: "text-teal-600 dark:text-teal-400" },
  pink: { bg: "bg-pink-100 dark:bg-pink-900/40", fg: "text-pink-600 dark:text-pink-400" },
  indigo: { bg: "bg-indigo-100 dark:bg-indigo-900/40", fg: "text-indigo-600 dark:text-indigo-400" },
  cyan: { bg: "bg-cyan-100 dark:bg-cyan-900/40", fg: "text-cyan-600 dark:text-cyan-400" },
  lime: { bg: "bg-lime-100 dark:bg-lime-900/40", fg: "text-lime-600 dark:text-lime-400" },
  amber: { bg: "bg-amber-100 dark:bg-amber-900/40", fg: "text-amber-600 dark:text-amber-400" },
  rose: { bg: "bg-rose-100 dark:bg-rose-900/40", fg: "text-rose-600 dark:text-rose-400" },
  violet: { bg: "bg-violet-100 dark:bg-violet-900/40", fg: "text-violet-600 dark:text-violet-400" },
  emerald: { bg: "bg-emerald-100 dark:bg-emerald-900/40", fg: "text-emerald-600 dark:text-emerald-400" },
  "slate-light": { bg: "bg-slate-50 dark:bg-slate-800/40", fg: "text-slate-500 dark:text-slate-300" },
  "blue-light": { bg: "bg-blue-50 dark:bg-blue-800/40", fg: "text-blue-500 dark:text-blue-300" },
  "green-light": { bg: "bg-green-50 dark:bg-green-800/40", fg: "text-green-500 dark:text-green-300" },
  "yellow-light": { bg: "bg-yellow-50 dark:bg-yellow-800/40", fg: "text-yellow-500 dark:text-yellow-300" },
  "purple-light": { bg: "bg-purple-50 dark:bg-purple-800/40", fg: "text-purple-500 dark:text-purple-300" },
  "orange-light": { bg: "bg-orange-50 dark:bg-orange-800/40", fg: "text-orange-500 dark:text-orange-300" },
  "red-light": { bg: "bg-red-50 dark:bg-red-800/40", fg: "text-red-500 dark:text-red-300" },
  "teal-light": { bg: "bg-teal-50 dark:bg-teal-800/40", fg: "text-teal-500 dark:text-teal-300" },
  "pink-light": { bg: "bg-pink-50 dark:bg-pink-800/40", fg: "text-pink-500 dark:text-pink-300" },
  "indigo-light": { bg: "bg-indigo-50 dark:bg-indigo-800/40", fg: "text-indigo-500 dark:text-indigo-300" },
  "cyan-light": { bg: "bg-cyan-50 dark:bg-cyan-800/40", fg: "text-cyan-500 dark:text-cyan-300" },
  "lime-light": { bg: "bg-lime-50 dark:bg-lime-800/40", fg: "text-lime-500 dark:text-lime-300" },
  "amber-light": { bg: "bg-amber-50 dark:bg-amber-800/40", fg: "text-amber-500 dark:text-amber-300" },
  "rose-light": { bg: "bg-rose-50 dark:bg-rose-800/40", fg: "text-rose-500 dark:text-rose-300" },
  "violet-light": { bg: "bg-violet-50 dark:bg-violet-800/40", fg: "text-violet-500 dark:text-violet-300" },
  "emerald-light": { bg: "bg-emerald-50 dark:bg-emerald-800/40", fg: "text-emerald-500 dark:text-emerald-300" },
  "slate-dark": { bg: "bg-slate-200 dark:bg-slate-950/60", fg: "text-slate-700 dark:text-slate-300" },
  "blue-dark": { bg: "bg-blue-200 dark:bg-blue-950/60", fg: "text-blue-700 dark:text-blue-300" },
  "green-dark": { bg: "bg-green-200 dark:bg-green-950/60", fg: "text-green-700 dark:text-green-300" },
  "yellow-dark": { bg: "bg-yellow-200 dark:bg-yellow-950/60", fg: "text-yellow-700 dark:text-yellow-300" },
  "purple-dark": { bg: "bg-purple-200 dark:bg-purple-950/60", fg: "text-purple-700 dark:text-purple-300" },
  "orange-dark": { bg: "bg-orange-200 dark:bg-orange-950/60", fg: "text-orange-700 dark:text-orange-300" },
  "red-dark": { bg: "bg-red-200 dark:bg-red-950/60", fg: "text-red-700 dark:text-red-300" },
  "teal-dark": { bg: "bg-teal-200 dark:bg-teal-950/60", fg: "text-teal-700 dark:text-teal-300" },
  "pink-dark": { bg: "bg-pink-200 dark:bg-pink-950/60", fg: "text-pink-700 dark:text-pink-300" },
  "indigo-dark": { bg: "bg-indigo-200 dark:bg-indigo-950/60", fg: "text-indigo-700 dark:text-indigo-300" },
  "cyan-dark": { bg: "bg-cyan-200 dark:bg-cyan-950/60", fg: "text-cyan-700 dark:text-cyan-300" },
  "lime-dark": { bg: "bg-lime-200 dark:bg-lime-950/60", fg: "text-lime-700 dark:text-lime-300" },
  "amber-dark": { bg: "bg-amber-200 dark:bg-amber-950/60", fg: "text-amber-700 dark:text-amber-300" },
  "rose-dark": { bg: "bg-rose-200 dark:bg-rose-950/60", fg: "text-rose-700 dark:text-rose-300" },
  "violet-dark": { bg: "bg-violet-200 dark:bg-violet-950/60", fg: "text-violet-700 dark:text-violet-300" },
  "emerald-dark": { bg: "bg-emerald-200 dark:bg-emerald-950/60", fg: "text-emerald-700 dark:text-emerald-300" },
};

export const COLOR_DOT: Record<SwatchColor, string> = {
  slate: "bg-slate-400",
  blue: "bg-blue-500",
  green: "bg-green-500",
  yellow: "bg-yellow-400",
  purple: "bg-purple-500",
  orange: "bg-orange-500",
  red: "bg-red-500",
  teal: "bg-teal-500",
  pink: "bg-pink-500",
  indigo: "bg-indigo-500",
  cyan: "bg-cyan-500",
  lime: "bg-lime-500",
  amber: "bg-amber-500",
  rose: "bg-rose-500",
  violet: "bg-violet-500",
  emerald: "bg-emerald-500",
  "slate-light": "bg-slate-300",
  "blue-light": "bg-blue-300",
  "green-light": "bg-green-300",
  "yellow-light": "bg-yellow-300",
  "purple-light": "bg-purple-300",
  "orange-light": "bg-orange-300",
  "red-light": "bg-red-300",
  "teal-light": "bg-teal-300",
  "pink-light": "bg-pink-300",
  "indigo-light": "bg-indigo-300",
  "cyan-light": "bg-cyan-300",
  "lime-light": "bg-lime-300",
  "amber-light": "bg-amber-300",
  "rose-light": "bg-rose-300",
  "violet-light": "bg-violet-300",
  "emerald-light": "bg-emerald-300",
  "slate-dark": "bg-slate-700",
  "blue-dark": "bg-blue-700",
  "green-dark": "bg-green-700",
  "yellow-dark": "bg-yellow-700",
  "purple-dark": "bg-purple-700",
  "orange-dark": "bg-orange-700",
  "red-dark": "bg-red-700",
  "teal-dark": "bg-teal-700",
  "pink-dark": "bg-pink-700",
  "indigo-dark": "bg-indigo-700",
  "cyan-dark": "bg-cyan-700",
  "lime-dark": "bg-lime-700",
  "amber-dark": "bg-amber-700",
  "rose-dark": "bg-rose-700",
  "violet-dark": "bg-violet-700",
  "emerald-dark": "bg-emerald-700",
};

/** Mappa colore -> CSS var per la torta multilivello (recharts richiede un valore letterale, non una classe Tailwind). */
export const SWATCH_CHART_COLOR: Record<SwatchColor, string> = {
  slate: "var(--swatch-slate)",
  blue: "var(--swatch-blue)",
  green: "var(--swatch-green)",
  yellow: "var(--swatch-yellow)",
  purple: "var(--swatch-purple)",
  orange: "var(--swatch-orange)",
  red: "var(--swatch-red)",
  teal: "var(--swatch-teal)",
  pink: "var(--swatch-pink)",
  indigo: "var(--swatch-indigo)",
  cyan: "var(--swatch-cyan)",
  lime: "var(--swatch-lime)",
  amber: "var(--swatch-amber)",
  rose: "var(--swatch-rose)",
  violet: "var(--swatch-violet)",
  emerald: "var(--swatch-emerald)",
  "slate-light": "var(--swatch-slate-light)",
  "blue-light": "var(--swatch-blue-light)",
  "green-light": "var(--swatch-green-light)",
  "yellow-light": "var(--swatch-yellow-light)",
  "purple-light": "var(--swatch-purple-light)",
  "orange-light": "var(--swatch-orange-light)",
  "red-light": "var(--swatch-red-light)",
  "teal-light": "var(--swatch-teal-light)",
  "pink-light": "var(--swatch-pink-light)",
  "indigo-light": "var(--swatch-indigo-light)",
  "cyan-light": "var(--swatch-cyan-light)",
  "lime-light": "var(--swatch-lime-light)",
  "amber-light": "var(--swatch-amber-light)",
  "rose-light": "var(--swatch-rose-light)",
  "violet-light": "var(--swatch-violet-light)",
  "emerald-light": "var(--swatch-emerald-light)",
  "slate-dark": "var(--swatch-slate-dark)",
  "blue-dark": "var(--swatch-blue-dark)",
  "green-dark": "var(--swatch-green-dark)",
  "yellow-dark": "var(--swatch-yellow-dark)",
  "purple-dark": "var(--swatch-purple-dark)",
  "orange-dark": "var(--swatch-orange-dark)",
  "red-dark": "var(--swatch-red-dark)",
  "teal-dark": "var(--swatch-teal-dark)",
  "pink-dark": "var(--swatch-pink-dark)",
  "indigo-dark": "var(--swatch-indigo-dark)",
  "cyan-dark": "var(--swatch-cyan-dark)",
  "lime-dark": "var(--swatch-lime-dark)",
  "amber-dark": "var(--swatch-amber-dark)",
  "rose-dark": "var(--swatch-rose-dark)",
  "violet-dark": "var(--swatch-violet-dark)",
  "emerald-dark": "var(--swatch-emerald-dark)",
};
