/**
 * components/domain/investments — barrel file
 *
 * Componenti della schermata Investimenti.
 */

export { PortfolioHeroCard } from "./portfolio-hero-card";
export type { PortfolioHeroCardProps } from "./portfolio-hero-card";
export { ValueBreakdownBar } from "./value-breakdown-bar";
export type { ValueBreakdownBarProps } from "./value-breakdown-bar";
export { INSTRUMENT_TYPE_COLOR, CURRENCY_COLORS } from "./instrument-colors";
export { PortfolioComposition } from "./portfolio-composition";
export type { CompositionGroup, PortfolioCompositionProps } from "./portfolio-composition";
export { PositionsList, STALE_PRICE_DAYS } from "./positions-list";
export type { PositionsListProps } from "./positions-list";
export { InvestmentTransactionsList, RECENT_OPERATION_MONTHS_LIMIT } from "./investment-transactions-list";
export type { InvestmentTransactionsListProps } from "./investment-transactions-list";
export { EditOperationDialog } from "./edit-operation-dialog";
export type { EditOperationDialogProps } from "./edit-operation-dialog";
export { OperationMonthGroup } from "./operation-month-group";
export type { OperationMonthGroupProps } from "./operation-month-group";
export { OperationRow } from "./operation-row";
export type { OperationRowProps } from "./operation-row";
export { OperationsTotals } from "./operations-totals";
export type { OperationsTotalsProps } from "./operations-totals";
export { GainText, formatSignedCurrency, formatSignedPct } from "./gain-text";
export type { GainTextProps } from "./gain-text";
export { InstrumentPicker } from "./instrument-picker";
export type { InstrumentPickerProps } from "./instrument-picker";
export { InstrumentManualForm } from "./instrument-manual-form";
export type { InstrumentManualFormProps } from "./instrument-manual-form";
export { RegisterOperationForm } from "./register-operation-form";
export type { RegisterOperationFormProps, RegisterOperationInitial } from "./register-operation-form";
export { PlansCard } from "./plans-card";
export type { PlansCardProps } from "./plans-card";
export { ManualPriceDialog } from "./manual-price-dialog";
export type { ManualPriceDialogProps } from "./manual-price-dialog";
export { prefillFromPlan } from "./register-operation-form.state";
export { InvestmentImportDialog } from "./import/investment-import-dialog";
export type { InvestmentImportDialogProps } from "./import/investment-import-dialog";
export { ReturnsCard } from "./returns-card";
export type { ReturnsCardProps } from "./returns-card";
export { ReturnsChart } from "./returns-chart";
export type { ReturnsChartProps } from "./returns-chart";
export { ReturnMetric } from "./return-metric";
export type { ReturnMetricProps } from "./return-metric";
export { BenchmarkSummary } from "./benchmark-summary";
export type { BenchmarkSummaryProps } from "./benchmark-summary";
export { BenchmarkDialog } from "./benchmark-dialog";
export type { BenchmarkDialogProps } from "./benchmark-dialog";
export { IncomeHistoryCard } from "./income-history-card";
export type { IncomeHistoryCardProps } from "./income-history-card";
export { ReturnHeatmapCard } from "./return-heatmap-card";
export type { ReturnHeatmapCardProps } from "./return-heatmap-card";
export { ReturnHeatmapGrid, heatmapCellColor } from "./return-heatmap-grid";
export type { ReturnHeatmapGridProps } from "./return-heatmap-grid";
export { RiskCard } from "./risk/risk-card";
export type { RiskCardProps } from "./risk/risk-card";
export { RiskMetric } from "./risk/risk-metric";
export type { RiskMetricProps } from "./risk/risk-metric";
export { DrawdownChart } from "./risk/drawdown-chart";
export type { DrawdownChartProps } from "./risk/drawdown-chart";
export { DiversificationCard } from "./diversification/diversification-card";
export type { DiversificationCardProps } from "./diversification/diversification-card";
export { BreakdownDialog } from "./diversification/breakdown-dialog";
export type { BreakdownDialogProps } from "./diversification/breakdown-dialog";
export { ExposureSourcesList } from "./diversification/exposure-sources-list";
export type { ExposureSourcesListProps } from "./diversification/exposure-sources-list";
export { OverlapCard } from "./diversification/overlap-card";
export type { OverlapCardProps } from "./diversification/overlap-card";
export { CorrelationMatrix, correlationColor } from "./diversification/correlation-matrix";
export type { CorrelationMatrixProps } from "./diversification/correlation-matrix";
export { SECTOR_COLOR, AREA_COLOR } from "./diversification/exposure-colors";
export { AllocationCard } from "./allocation/allocation-card";
export type { AllocationCardProps } from "./allocation/allocation-card";
export { TargetsDialog } from "./allocation/targets-dialog";
export type { TargetsDialogProps } from "./allocation/targets-dialog";
export { ContributionSuggestions } from "./allocation/contribution-suggestions";
export type { ContributionSuggestionsProps } from "./allocation/contribution-suggestions";
export { InvestmentsActionsProvider, useInvestmentsActions } from "./investments-actions";
export type { InvestmentsActions } from "./investments-actions";
export { InvestmentsTabs, INVESTMENTS_TABS, INVESTMENTS_TAB_ICON_SIZE } from "./investments-tabs";
export type { InvestmentsTab, InvestmentsTabsProps } from "./investments-tabs";
export { MonthBars } from "./income/month-bars";
export type { MonthBar, MonthBarsProps } from "./income/month-bars";
export { IncomeForecastCard } from "./income/income-forecast-card";
export type { IncomeForecastCardProps } from "./income/income-forecast-card";
export { MissingIncomeCard } from "./income/missing-income-card";
export type { MissingIncomeCardProps } from "./income/missing-income-card";
export { IncomeMonthsCard } from "./income/income-months-card";
export type { IncomeMonthsCardProps } from "./income/income-months-card";
export { IncomeInstrumentsCard } from "./income/income-instruments-card";
export type { IncomeInstrumentsCardProps } from "./income/income-instruments-card";
export { InstrumentSettingsDialog } from "./taxes/instrument-settings-dialog";
export type { InstrumentSettingsDialogProps } from "./taxes/instrument-settings-dialog";
export { TaxRegimeCard } from "./taxes/tax-regime-card";
export type { TaxRegimeCardProps } from "./taxes/tax-regime-card";
export { TaxYearCard } from "./taxes/tax-year-card";
export type { TaxYearCardProps } from "./taxes/tax-year-card";
export { LossCarryforwardCard } from "./taxes/loss-carryforward-card";
export type { LossCarryforwardCardProps } from "./taxes/loss-carryforward-card";
export { SaleSimulatorCard } from "./taxes/sale-simulator-card";
export type { SaleSimulatorCardProps } from "./taxes/sale-simulator-card";
export { TaxOpportunitiesCard } from "./taxes/tax-opportunities-card";
export type { TaxOpportunitiesCardProps } from "./taxes/tax-opportunities-card";
export { InstrumentTaxListCard } from "./taxes/instrument-tax-list-card";
export type { InstrumentTaxListCardProps } from "./taxes/instrument-tax-list-card";
export { useRegisterFromPlan } from "./investments-actions";
export { InvestmentsViewGate } from "./investments-view-gate";
export type { InvestmentsViewGateProps } from "./investments-view-gate";
export * from "./titles";

export { BrokerStatements } from "./broker-statements";
