/** Voce del dizionario: se il testo normalizzato (maiuscolo, senza accenti) combacia, il merchant è `name`. */
export interface MerchantAlias {
  pattern: RegExp;
  name: string;
}

const a = (pattern: string, name: string): MerchantAlias => ({ pattern: new RegExp(pattern), name });

/**
 * Dizionario dei merchant e delle voci bancarie più comuni in Italia. L'ordine conta: vince la prima
 * voce che combacia, quindi le più specifiche stanno prima. Si estende aggiungendo righe (idealmente
 * da un'estrazione di transazioni reali), senza toccare la logica di estrazione.
 */
export const MERCHANT_ALIASES: readonly MerchantAlias[] = [
  // Voci bancarie senza merchant
  a("\\b(PRELIEVO|PRELEVAMENTO)\\b.*\\b(ATM|BANCOMAT|CONTANTI|SPORTELLO)\\b|\\bPRELIEVO CONTANTI\\b", "Prelievo contanti"),
  a("\\bVERSAMENTO\\b.*\\b(CONTANTI|ATM)\\b", "Versamento contanti"),
  a("\\bIMPOSTA (DI )?BOLLO\\b|\\bBOLLO (CONTO|DEPOSITO|TITOLI)\\b", "Imposta di bollo"),
  a("\\b(CANONE|SPESE) (MENSILE|TRIMESTRALE|TENUTA CONTO|CONTO|CARTA|GESTIONE)\\b|\\bCOMMISSION[EI]\\b", "Commissioni bancarie"),
  a("\\b(EMOLUMENTI|STIPENDIO|COMPETENZE)\\b", "Stipendio"),
  a("\\bAGENZIA (DELLE )?ENTRATE\\b|\\bF24\\b", "Agenzia delle Entrate"),
  a("\\bINPS\\b", "INPS"),
  // Pagamenti, marketplace e servizi digitali
  a("\\b(AMZN|AMAZON)\\b.*\\bPRIME\\b|\\bPRIME VIDEO\\b", "Amazon Prime"),
  a("\\b(AMZN|AMAZON)\\b", "Amazon"),
  a("\\bNETFLIX", "Netflix"),
  a("\\bSPOTIFY", "Spotify"),
  a("\\bDISNEY\\b", "Disney+"),
  a("\\bDAZN\\b", "DAZN"),
  a("\\bAPPLE\\.COM|\\bITUNES\\b|\\bAPPLE (STORE|MUSIC|SERVICES)\\b", "Apple"),
  a("\\bGOOGLE\\b.*\\b(YOUTUBE|ONE|STORAGE)\\b|\\bYOUTUBE\\b", "Google / YouTube"),
  a("\\bGOOGLE\\b", "Google"),
  a("\\bMICROSOFT\\b|\\bMSFT\\b", "Microsoft"),
  a("\\bOPENAI\\b|\\bCHATGPT\\b", "OpenAI"),
  a("\\bADOBE\\b", "Adobe"),
  a("\\bDROPBOX\\b", "Dropbox"),
  a("\\bPLAYSTATION\\b|\\bSONY INTERACTIVE\\b", "PlayStation"),
  a("\\bSTEAM(POWERED| GAMES)?\\b|\\bVALVE\\b", "Steam"),
  a("\\bNINTENDO\\b", "Nintendo"),
  a("\\bEBAY\\b", "eBay"),
  a("\\bZALANDO\\b", "Zalando"),
  a("\\bSHEIN\\b", "Shein"),
  a("\\bALIEXPRESS\\b", "AliExpress"),
  a("\\bVINTED\\b", "Vinted"),
  a("\\bSUBITO\\b", "Subito"),
  a("\\bSATISPAY\\b", "Satispay"),
  a("\\bREVOLUT\\b", "Revolut"),
  a("\\bPOSTE ?PAY\\b|\\bPOSTE ITALIANE\\b", "Poste Italiane"),
  // Cibo e consegne
  a("\\bJUST ?EAT\\b", "Just Eat"),
  a("\\bGLOVO\\b", "Glovo"),
  a("\\bDELIVEROO\\b", "Deliveroo"),
  a("\\bUBER ?EATS\\b", "Uber Eats"),
  a("\\bMC ?DONALD'?S?\\b|\\bMCDONALD\\b", "McDonald's"),
  a("\\bBURGER ?KING\\b", "Burger King"),
  a("\\bSTARBUCKS\\b", "Starbucks"),
  a("\\bAUTOGRILL\\b", "Autogrill"),
  a("\\bGROM\\b", "Grom"),
  // Supermercati e casa
  a("\\bESSELUNGA\\b", "Esselunga"),
  a("\\bCONAD\\b", "Conad"),
  a("\\bCOOP\\b", "Coop"),
  a("\\bCARREFOUR\\b", "Carrefour"),
  a("\\bLIDL\\b", "Lidl"),
  a("\\bEUROSPIN\\b", "Eurospin"),
  a("\\bMD (DISCOUNT|S ?P ?A)\\b|\\bMD SPA\\b", "MD"),
  a("\\bPAM\\b|\\bPANORAMA\\b", "Pam"),
  a("\\bIPER( |$)|\\bIPERCOOP\\b", "Iper"),
  a("\\bDESPAR\\b|\\bEUROSPAR\\b|\\bINTERSPAR\\b|\\bSPAR\\b", "Despar"),
  a("\\bALDI\\b", "Aldi"),
  a("\\bNATURASI\\b", "NaturaSì"),
  a("\\bIKEA\\b", "IKEA"),
  a("\\bLEROY ?MERLIN\\b", "Leroy Merlin"),
  a("\\bBRICO(CENTER|MAN|IO)\\b", "Brico"),
  a("\\bDECATHLON\\b", "Decathlon"),
  a("\\bMEDIA ?WORLD\\b", "MediaWorld"),
  a("\\bUNIEURO\\b", "Unieuro"),
  a("\\bSEPHORA\\b", "Sephora"),
  a("\\bDOUGLAS\\b", "Douglas"),
  a("\\bH ?& ?M\\b|\\bHENNES\\b", "H&M"),
  a("\\bZARA\\b", "Zara"),
  a("\\bOVS\\b", "OVS"),
  a("\\bTIGER\\b", "Tiger"),
  // Trasporti e carburante
  a("\\bTRENITALIA\\b", "Trenitalia"),
  a("\\bITALO\\b.*\\b(NTV|TRENO|BIGLIETTO)\\b|\\bNTV\\b", "Italo"),
  a("\\bFLIXBUS\\b", "FlixBus"),
  a("\\bTELEPASS\\b", "Telepass"),
  a("\\bAUTOSTRADE\\b|\\bAUTOSTRADA\\b", "Autostrade"),
  a("\\bRYANAIR\\b", "Ryanair"),
  a("\\bEASY ?JET\\b", "easyJet"),
  a("\\bWIZZ ?AIR\\b", "Wizz Air"),
  a("\\bITA AIRWAYS\\b|\\bALITALIA\\b", "ITA Airways"),
  a("\\bBOOKING\\.COM\\b|\\bBOOKING COM\\b", "Booking.com"),
  a("\\bAIRBNB\\b", "Airbnb"),
  a("\\bUBER\\b", "Uber"),
  a("\\bFREE ?NOW\\b|\\bMYTAXI\\b", "FreeNow"),
  a("\\bENI( STATION| LIVE)?\\b", "Eni"),
  a("\\bQ8\\b|\\bKUWAIT PETROLEUM\\b", "Q8"),
  a("\\bTAMOIL\\b", "Tamoil"),
  a("\\bIP (STATION|MATIC)\\b|\\bIPERSTATION\\b", "IP"),
  a("\\bAPCOA\\b|\\bEASYPARK\\b|\\bPARKING\\b|\\bPARCHEGGIO\\b", "Parcheggio"),
  // Utenze e telefonia
  a("\\bENEL( ENERGIA| X)?\\b", "Enel"),
  a("\\bEDISON\\b", "Edison"),
  a("\\bA2A\\b", "A2A"),
  a("\\bHERA( COMM)?\\b", "Hera"),
  a("\\bIREN\\b|\\bIREN MERCATO\\b", "Iren"),
  a("\\bSORGENIA\\b", "Sorgenia"),
  a("\\bACEA\\b", "Acea"),
  a("\\bPLENITUDE\\b", "Plenitude"),
  a("\\bTIM\\b|\\bTELECOM ITALIA\\b", "TIM"),
  a("\\bVODAFONE\\b", "Vodafone"),
  a("\\bWIND ?TRE\\b|\\bWIND\\b", "WindTre"),
  a("\\bFASTWEB\\b", "Fastweb"),
  a("\\bILIAD\\b", "Iliad"),
  a("\\bHO\\.? ?MOBILE\\b", "Ho. Mobile"),
  a("\\bKENA ?MOBILE\\b", "Kena Mobile"),
  a("\\bSKY( ITALIA)?\\b", "Sky"),
  // Assicurazioni, salute, sport
  a("\\bUNIPOL(SAI)?\\b", "UnipolSai"),
  a("\\bGENERALI\\b", "Generali"),
  a("\\bALLIANZ\\b", "Allianz"),
  a("\\bAXA\\b", "AXA"),
  a("\\bFARMACIA\\b", "Farmacia"),
  a("\\bBASIC ?FIT\\b", "Basic-Fit"),
  a("\\bTECHNOGYM\\b", "Technogym"),
];
